
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * List all available audio-input devices.
 * 
 * Routes through `Orchestrator::list_devices`, which wraps the FFI-bound
 * cpal enumeration in `spawn_blocking`. This keeps `ipc-bridge`'s
 * dependency table honest: it depends on `orchestrator`, not directly on
 * `audio-capture`.
 */
async listDevices() : Promise<Result<AudioDevice[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start a new recording session.
 * 
 * `device_id = None` → use the device configured in settings, or the OS
 * default if none is configured.
 * 
 * Returns the new `MeetingId` on success.
 */
async startRecording(deviceId: string | null) : Promise<Result<MeetingId, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_recording", { deviceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pause the current recording.
 */
async pauseRecording() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume after a pause.
 */
async resumeRecording() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the current recording and finalise the meeting.
 * 
 * Returns the completed `MeetingMeta` on success.
 */
async stopRecording() : Promise<Result<MeetingMeta, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return a snapshot of the current recording state.
 */
async getRecordingState() : Promise<Result<RecordingState, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recording_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the current application settings.
 */
async getSettings() : Promise<Result<Settings, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist updated application settings.
 * 
 * Broadcasts the change to all `SettingsHandle` subscribers.
 */
async updateSettings(settings: Settings) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all known models with their current runtime status.
 * 
 * Routes through `Orchestrator::list_models`, which wraps `ModelRegistry::list_models`
 * so that `ipc-bridge` does not need a direct `model-registry` dependency.
 */
async listModels() : Promise<Result<ModelStatus[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ensure a model is downloaded and hash-verified.
 * 
 * Returns `Ok(())` when the model is ready for use. Starts a download if the
 * model is absent; the webview tracks granular progress via
 * `AppEvent::ModelDownloadProgress` events emitted on the broadcast channel.
 * 
 * Routes through `Orchestrator::ensure_model`, preserving the dependency-table
 * invariant that `ipc-bridge` does not depend directly on `model-registry`.
 */
async ensureModel(modelId: ModelId) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist a meeting's notes (`notes.json` + `notes.md`).
 * 
 * Routes **directly** to `persistence::NotesStore` against
 * `IpcState::meetings_dir` — notes I/O is independent of the live recording
 * pipeline (see `architecture/components.md`, `persistence` "Phase 3 surface
 * growth — notes"), so the orchestrator is not involved. The blocking
 * filesystem write runs on `spawn_blocking` per the threading model.
 * 
 * `notes_json` is parsed from a `String` into a `serde_json::Value`; an
 * invalid JSON string is rejected as `AppError::InvalidInput`.
 */
async saveNotes(meetingId: MeetingId, notesJson: string, notesMarkdown: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_notes", { meetingId, notesJson, notesMarkdown }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load a meeting's persisted notes, or `None` when no notes have been saved.
 * 
 * Routes directly to `persistence::NotesStore`; the loaded opaque
 * `serde_json::Value` is re-serialised back to a `String` for the wire (see
 * [`NotesDoc`]).
 */
async loadNotes(meetingId: MeetingId) : Promise<Result<NotesDoc | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_notes", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all meetings for the meeting-list view (FR-33), most-recent first.
 * 
 * Reads straight from the libsql `index.db` ([`MeetingIndex::list_meetings`])
 * — a cheap projection that never loads a meeting's full transcript. The index
 * is async (libsql/tokio); the future is awaited here, never `block_on`'d.
 */
async listMeetings() : Promise<Result<MeetingListEntry[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meetings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a meeting, returning its full restorable [`MeetingState`]
 * (metadata + transcript + optional notes).
 * 
 * Resolves the per-meeting folder under `IpcState::meetings_dir` and assembles
 * the state via `persistence::read_meeting_state`. The blocking `std::fs` reads
 * run on `spawn_blocking` per the threading model — the index is not consulted
 * (the folder is authoritative for the full state).
 */
async openMeeting(meetingId: MeetingId) : Promise<Result<MeetingState, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_meeting", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a meeting: updates `metadata.json` (authoritative) then the index row.
 * 
 * Routes to `persistence::meeting_ops::rename_meeting`, which keeps the on-disk
 * folder and the index consistent (see `architecture/components.md`,
 * `persistence` "Phase 4 surface growth — meeting ops").
 */
async renameMeeting(meetingId: MeetingId, title: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_meeting", { meetingId, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a meeting: removes the folder then the index row.
 * 
 * Routes to `persistence::meeting_ops::delete_meeting`.
 */
async deleteMeeting(meetingId: MeetingId) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-run transcription for a meeting offline (FR-33 action).
 * 
 * Routes to `Orchestrator::re_transcribe`, which decodes the meeting audio and
 * drives the same batched-VAD + ASR pipeline the live recorder uses, rewrites
 * `transcript.json`, refreshes the index row, and emits
 * `AppEvent::TranscriptSegment` events. Refused while a recording is in
 * progress (the orchestrator returns `AppError::InvalidInput`). The index
 * handle is shared from `IpcState` so the orchestrator need not own one.
 */
async reTranscribe(meetingId: MeetingId) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("re_transcribe", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-run summarisation for a meeting (FR-33 action) — **Phase 5 stub**.
 * 
 * The `summariser` crate (Phase 5) produces `summary.md` and emits
 * `AppEvent::SummaryReady`. Until then this command returns
 * `AppError::Unsupported` so the command surface + generated binding exist for
 * Stream B's meeting-list action without a backing implementation.
 */
async reSummarise(meetingId: MeetingId) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("re_summarise", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
appEventPayload: AppEventPayload
}>({
appEventPayload: "app-event-payload"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * The shared error type that crosses crate boundaries.
 * 
 * Per-crate `Error` enums (defined with `thiserror` in their owning
 * crate) provide structured `From` impls into `AppError`. The webview
 * only ever sees `AppError`. Variants have stable discriminants — the
 * TypeScript binding is generated from this enum, so renaming or
 * removing a variant is a breaking IPC change.
 */
export type AppError = { code: "io"; context: string } | { code: "model_load"; model_id: string; context: string } | { code: "model_not_found"; model_id: string } | { code: "model_download"; context: string } | { code: "inference"; backend: string; context: string } | { code: "invalid_input"; context: string } | { code: "cancelled" } | { code: "unsupported"; context: string } | { code: "internal"; context: string }
/**
 * Events emitted from the Rust core to the webview via tauri-specta.
 * 
 * Adding a variant requires updating `ipc-bridge` (encoder), the webview
 * IPC client (decoder), and re-running the bindings generation step.
 */
export type AppEvent = 
/**
 * Audio meter sample emitted at ~30 Hz while recording. Carries both
 * peak and RMS so the UI can pick the rendering it wants without an
 * extra round-trip.
 */
{ kind: "audio_meter"; frame: AudioMeterFrame } | 
/**
 * The available audio-input device list changed (hotplug or default
 * device switch). The webview should re-query `list_devices`.
 */
{ kind: "devices_changed" } | 
/**
 * Recording state changed.
 */
{ kind: "state_changed"; state: RecordingState } | 
/**
 * A new transcript segment was produced.
 */
{ kind: "transcript_segment"; meeting_id: MeetingId; segment: Segment } | 
/**
 * The live recording clock advanced. Emitted at a throttled rate
 * (~5 Hz) while recording. `clock_ms` is the capture-sample,
 * pause-*excluding* offset from the start of the recording — the same
 * timeline as `Segment::start_ms` and `AudioChunk::start_ms`. The notes
 * editor stamps paragraph anchors (`data-anchor-ms`) from this value so
 * anchors line up with transcript segments; do NOT derive anchors from
 * `Date.now() - started_at_ms` (that is pause-including wall-clock).
 */
{ kind: "recording_clock"; meeting_id: MeetingId; clock_ms: number } | 
/**
 * Diarization finished assigning speakers to a meeting's segments.
 */
{ kind: "diarization_complete"; meeting_id: MeetingId; speaker_count: number } | 
/**
 * Summary generation finished; `summary.md` now exists for this meeting.
 */
{ kind: "summary_ready"; meeting_id: MeetingId } | 
/**
 * Model download progress, used by the first-run flow.
 */
{ kind: "model_download_progress"; model_id: ModelId; bytes_done: number; bytes_total: number | null } | 
/**
 * User-visible settings changed; subscribers should re-read.
 */
{ kind: "settings_changed" } | 
/**
 * A recoverable error occurred during a background task. The pipeline
 * continues; the webview shows a notification.
 */
{ kind: "error_occurred"; error: AppError }
/**
 * Typed wrapper that gives `AppEvent` a stable tauri-specta event name.
 * 
 * The `Event` derive assigns the wire name `"app-event-payload"`. The
 * `#[serde(transparent)]` attribute means the wrapper is invisible on the
 * wire — the JSON shape is exactly `AppEvent`'s own tagged-enum
 * representation.
 */
export type AppEventPayload = AppEvent
/**
 * One audio-input device exposed to the device-picker UI.
 * 
 * `id` is a stable, opaque string the IPC layer round-trips back to
 * `audio-capture` to select the device. Format is implementation-defined
 * (cpal device-name plus host index on the Rust side). `name` is the
 * display label; `is_default` reflects the OS's default-input choice at
 * query time.
 */
export type AudioDevice = { id: string; name: string; is_default: boolean }
/**
 * Audio-file format descriptor captured at write time. Phase 1 writes
 * Opus 16 kHz mono; downstream phases re-decode using these fields.
 */
export type AudioFormat = { codec: string; sample_rate: number; channels: number; bitrate_kbps?: number | null }
/**
 * One audio-meter sample emitted at ~30 Hz while recording.
 * 
 * `peak` is the maximum absolute sample magnitude in [0.0, 1.0] over the
 * most-recent meter window (~33 ms of audio). `rms` is the root-mean-square
 * over the same window. Consumers may render either; both are cheap to
 * compute alongside capture.
 */
export type AudioMeterFrame = { peak: number; rms: number }
/**
 * Error type returned from every Tauri command in `ipc-bridge`.
 * 
 * Carries the same discriminants as `common::AppError` and serialises to the
 * same JSON shape (`{"code": "...", ...}`), so the TypeScript binding is
 * stable even though the derive lives here rather than in `common`.
 */
export type IpcError = { code: "io"; context: string } | { code: "model_load"; model_id: string; context: string } | { code: "model_not_found"; model_id: string } | { code: "model_download"; context: string } | { code: "inference"; backend: string; context: string } | { code: "invalid_input"; context: string } | { code: "cancelled" } | { code: "unsupported"; context: string } | { code: "internal"; context: string }
/**
 * Stable identifier for a meeting on disk. UUIDv4.
 */
export type MeetingId = string
/**
 * A summary row for the meeting-list view (FR-33). Cheap to query from the
 * `persistence` index without loading a meeting's full transcript.
 */
export type MeetingListEntry = { id: MeetingId; title: string; 
/**
 * RFC3339 start timestamp (wall-clock), mirroring `MeetingMeta::started_at`.
 */
started_at: string; duration_ms: number; speaker_count: number; 
/**
 * Short transcript excerpt for the list preview, when available.
 */
excerpt?: string | null }
/**
 * Per-meeting metadata persisted as `metadata.json`.
 * 
 * Timestamps are ISO 8601 strings to avoid pulling `chrono` into `common`.
 * Consumers parse as needed.
 */
export type MeetingMeta = { uuid: MeetingId; title: string; started_at: string; ended_at: string | null; duration_ms: number; speaker_count: number; audio_format: AudioFormat; asr_model: ModelDescriptor | null; llm_model: ModelDescriptor | null; diarizer: ModelDescriptor | null; app_version: string }
/**
 * The full restorable state of a meeting, assembled by `persistence` for
 * `open_meeting`: metadata, transcript segments, and the notes document
 * (absent when the meeting has no saved notes yet).
 */
export type MeetingState = { meta: MeetingMeta; transcript: Segment[]; notes?: NotesDocument | null }
export type ModelDescriptor = { name: string; quantisation: string | null; version: string }
/**
 * Stable identifier for a model in the registry.
 * 
 * Examples: `"qwen3-asr-1.7b-q8_0"`, `"qwen2.5-3b-instruct-q4_k_m"`,
 * `"silero-vad-v4"`, `"sherpa-pyannote-segmentation-3-0"`.
 */
export type ModelId = string
/**
 * Coarse model classification — drives the per-kind cache subdirectory
 * under `{app-data}/models/{kind}/` (see `architecture/cross-cutting.md`
 * "Filesystem layout").
 */
export type ModelKind = "asr" | "llm" | "diarize"
export type ModelStatus = { id: ModelId; kind: ModelKind; display_name: string; status: ModelStatusState }
/**
 * Runtime state of one model on this user's machine.
 */
export type ModelStatusState = 
/**
 * Files are present and hashes match. `local_dir` is the cache
 * directory absolute path.
 */
{ state: "available"; local_dir: string } | 
/**
 * Files are missing or partial. `bytes_present` and `bytes_total`
 * are summed across the manifest's `files`.
 */
{ state: "missing"; bytes_present: number; bytes_total: number } | 
/**
 * A download is in progress. The webview tracks granular progress
 * via `AppEvent::ModelDownloadProgress` events; this state is the
 * snapshot at query time.
 */
{ state: "downloading"; bytes_done: number; bytes_total: number } | 
/**
 * A previous download or hash check failed. `message` is a stable
 * human-readable string suitable for surfacing in UI.
 */
{ state: "failed"; message: string }
/**
 * A persisted notes document returned by [`load_notes`].
 * 
 * `notes_json` carries the Tiptap/ProseMirror document **as a `String`**, not
 * a `serde_json::Value`: a bare `serde_json::Value` does not derive
 * `specta::Type`, so it cannot cross the tauri-specta boundary directly. The
 * webview owns the (de)serialisation of this opaque document; `persistence`
 * stores it verbatim (the Phase-4 transcript-chip opacity guarantee). The
 * `String`-over-the-wire choice keeps the IPC contract typed without forcing a
 * Rust-side Tiptap model.
 */
export type NotesDoc = { notes_json: string; notes_markdown: string }
/**
 * The notes document as it crosses the IPC boundary.
 * 
 * `notes_json` is the Tiptap document serialised to a JSON **string** —
 * `serde_json::Value` does not derive `specta::Type`, so the opaque document
 * rides the wire as a string and the webview owns its (de)serialisation.
 * `persistence` stores it verbatim (the transcript-chip opacity guarantee).
 * This is the canonical wire-facing notes carrier; `ipc-bridge` re-uses it.
 */
export type NotesDocument = { notes_json: string; notes_markdown: string }
/**
 * Top-level state of the recording pipeline. Emitted to the webview on
 * transitions via `AppEvent::StateChanged`.
 * 
 * **Timestamp semantics:** `started_at_ms` and `paused_at_ms` are
 * **wall-clock milliseconds since the Unix epoch** (UTC), not
 * recording-clock offsets. The webview can compute live elapsed-recording
 * duration as `Date.now() - started_at_ms` (subtracting accumulated
 * pause-time client-side if needed). Phase-internal timestamps that are
 * genuinely recording-clock (e.g. `Segment::start_ms`, `AudioChunk::start_ms`)
 * remain recording-clock — those are a different namespace and carry the
 * `_ms` suffix without the `_at` infix.
 * 
 * **Do NOT use `Date.now() - started_at_ms` as a paragraph-anchor source.**
 * That wall-clock delta is pause-*including* and drifts from the audio
 * timeline. Notes paragraph anchors must be stamped from
 * `AppEvent::RecordingClock { clock_ms }`, which is the capture-sample,
 * pause-*excluding* clock (same origin as `Segment::start_ms`). The
 * `started_at_ms` recipe above is for elapsed-time *display* only.
 */
export type RecordingState = { kind: "idle" } | { kind: "recording"; meeting_id: MeetingId; started_at_ms: number } | { kind: "paused"; meeting_id: MeetingId; paused_at_ms: number } | { kind: "stopping"; meeting_id: MeetingId }
/**
 * One transcript segment with optional speaker assignment.
 * 
 * Speaker is populated by the `Diarizer` impl post-hoc; ASR backends
 * leave it `None`.
 */
export type Segment = { start_ms: number; end_ms: number; text: string; speaker_id?: string | null; confidence?: number | null; words: WordTimestamp[] }
/**
 * Application settings.
 * 
 * Fields added in later phases live in their respective phase plans.
 * Do **not** add ASR model selection, summary system-prompt, or telemetry
 * fields here — those are Phase 2+ concerns.
 */
export type Settings = { 
/**
 * The preferred audio-input device, identified by the opaque id
 * returned by `audio-capture::AudioCaptureManager::list_devices`.
 * `None` means "use the OS default".
 */
input_device_id?: string | null; 
/**
 * UI colour-scheme preference.
 */
theme?: Theme; 
/**
 * Root directory for meeting data.  `None` means "use the platform
 * default app-data directory" (resolved by `app-main`).
 * 
 * `specta` lacks a built-in `Type` impl for `PathBuf`; the explicit
 * `#[specta(type = Option<String>)]` hint preserves the same wire
 * shape (UTF-8 path string or `null`) the manual mirror produced.
 */
data_directory?: string | null; 
/**
 * If `true`, the main window starts hidden; accessible via the tray icon.
 */
start_hidden?: boolean; 
/**
 * Notes-editor autosave interval, in seconds (FR-18/FR-35).
 * 
 * The editor debounces autosaves of `notes.json`/`notes.md` to this
 * cadence. Defaults to 5 s; an older store written before this field
 * existed deserialises to the default via `#[serde(default = ...)]`.
 */
autosave_interval_secs?: number }
/**
 * UI colour-scheme preference.
 */
export type Theme = "light" | "dark" | 
/**
 * Follow the OS preference (default).
 */
"system"
/**
 * Optional per-word timestamp data when the ASR model supports it.
 */
export type WordTimestamp = { start_ms: number; end_ms: number; text: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
