
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * List all available audio-input devices.
 * 
 * This is a direct call to `AudioCaptureManager::list_devices()` — no
 * orchestrator involvement.
 */
async listDevices() : Promise<Result<AudioDeviceType[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start a new recording session.
 * 
 * `device_id = None` → use the device configured in settings, or the OS
 * default if none is configured.
 * 
 * Returns the new `MeetingId` on success.
 */
async startRecording(deviceId: string | null) : Promise<Result<MeetingIdType, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_recording", { deviceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pause the current recording.
 */
async pauseRecording() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume after a pause.
 */
async resumeRecording() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the current recording and finalise the meeting.
 * 
 * Returns the completed `MeetingMeta` on success.
 */
async stopRecording() : Promise<Result<MeetingMetaType, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return a snapshot of the current recording state.
 */
async getRecordingState() : Promise<Result<RecordingStateType, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recording_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the current application settings.
 */
async getSettings() : Promise<Result<SettingsType, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist updated application settings.
 * 
 * Broadcasts the change to all `SettingsHandle` subscribers.
 */
async updateSettings(settings: SettingsType) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
appEventPayload: AppEventPayload
}>({
appEventPayload: "app-event-payload"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Typed wrapper that gives `AppEventType` a stable tauri-specta event name.
 * 
 * The `Event` derive assigns the wire name `"app-event-payload"`.
 * The serde shape is identical to `common::AppEvent` because `AppEventType`
 * is a full mirror of `AppEvent`.
 * 
 * Once `common` gains `specta::Type` derives, this type can be replaced
 * by registering `AppEvent` directly in `collect_events!`.
 */
export type AppEventPayload = AppEventType
/**
 * specta-typed mirror of `common::AppEvent`.
 * 
 * This is the fully-typed version of the event payload, using the mirror
 * types above.  The `AppEventPayload` wrapper in `events.rs` serialises
 * `AppEvent` via `serde` and then deserialises into this type's shape;
 * the JSON wire representations are identical because both are derived from
 * the same serde attributes.
 */
export type AppEventType = { kind: "audio_meter"; frame: AudioMeterFrameType } | { kind: "devices_changed" } | { kind: "state_changed"; state: RecordingStateType } | { kind: "transcript_segment"; meeting_id: MeetingIdType; segment: SegmentType } | { kind: "diarization_complete"; meeting_id: MeetingIdType; speaker_count: number } | { kind: "summary_ready"; meeting_id: MeetingIdType } | { kind: "model_download_progress"; model_id: string; bytes_done: number; bytes_total: number | null } | { kind: "settings_changed" } | { kind: "error_occurred"; error: IpcErrorType }
/**
 * specta-typed mirror of `common::AudioDevice`.
 */
export type AudioDeviceType = { id: string; name: string; is_default: boolean }
/**
 * specta-typed mirror of `common::AudioFormat`.
 */
export type AudioFormatType = { codec: string; sample_rate: number; channels: number; bitrate_kbps: number | null }
/**
 * specta-typed mirror of `common::AudioMeterFrame`.
 */
export type AudioMeterFrameType = { peak: number; rms: number }
/**
 * Error type returned from every Tauri command in `ipc-bridge`.
 * 
 * Carries the same discriminants as `common::AppError` and serialises to the
 * same JSON shape (`{"code": "...", ...}`), so the TypeScript binding is
 * stable even though the derive lives here rather than in `common`.
 */
export type IpcError = { code: "io"; context: string } | { code: "model_load"; model_id: string; context: string } | { code: "model_not_found"; model_id: string } | { code: "model_download"; context: string } | { code: "inference"; backend: string; context: string } | { code: "invalid_input"; context: string } | { code: "cancelled" } | { code: "unsupported"; context: string } | { code: "internal"; context: string }
/**
 * specta-typed mirror of `common::AppError` for embedding in events.
 * 
 * Identical shape to `error::IpcError` but kept separate to avoid a
 * circular dependency in the specta type graph (IpcError appears in command
 * results; IpcErrorType appears inside the AppEventType::ErrorOccurred
 * variant).
 */
export type IpcErrorType = { code: "io"; context: string } | { code: "model_load"; model_id: string; context: string } | { code: "model_not_found"; model_id: string } | { code: "model_download"; context: string } | { code: "inference"; backend: string; context: string } | { code: "invalid_input"; context: string } | { code: "cancelled" } | { code: "unsupported"; context: string } | { code: "internal"; context: string }
/**
 * specta-typed mirror of `common::MeetingId`.
 * 
 * Represented as a transparent `String` because `Uuid` does not implement
 * `specta::Type` in the workspace-pinned version of specta (rc.22 requires
 * the "uuid" feature which would need a workspace Cargo.toml edit).  The
 * JSON wire representation is identical — `Uuid` serialises as a
 * hyphenated lowercase UUID string.
 */
export type MeetingIdType = string
/**
 * specta-typed mirror of `common::MeetingMeta`.
 */
export type MeetingMetaType = { uuid: MeetingIdType; title: string; started_at: string; ended_at: string | null; duration_ms: number; speaker_count: number; audio_format: AudioFormatType; asr_model: ModelDescriptorType | null; llm_model: ModelDescriptorType | null; diarizer: ModelDescriptorType | null; app_version: string }
/**
 * specta-typed mirror of `common::ModelDescriptor`.
 */
export type ModelDescriptorType = { name: string; quantisation: string | null; version: string }
/**
 * specta-typed mirror of `common::RecordingState`.
 */
export type RecordingStateType = { kind: "idle" } | { kind: "recording"; meeting_id: MeetingIdType; started_at_ms: number } | { kind: "paused"; meeting_id: MeetingIdType; paused_at_ms: number } | { kind: "stopping"; meeting_id: MeetingIdType }
/**
 * specta-typed mirror of `common::Segment`.
 */
export type SegmentType = { start_ms: number; end_ms: number; text: string; speaker_id?: string | null; confidence?: number | null; words: WordTimestampType[] }
/**
 * specta-typed mirror of `settings::Settings`.
 * 
 * `data_directory` is mapped to `Option<String>` (PathBuf has no
 * specta::Type impl).  The conversion from `Settings` serialises the path as
 * a UTF-8 string; the reverse parses it back.
 */
export type SettingsType = { input_device_id?: string | null; theme?: ThemeType; 
/**
 * Serialised form of `Settings::data_directory` (`PathBuf` → `String`).
 */
data_directory?: string | null; start_hidden?: boolean }
/**
 * specta-typed mirror of `settings::Theme`.
 */
export type ThemeType = "light" | "dark" | "system"
/**
 * specta-typed mirror of `common::WordTimestamp`.
 */
export type WordTimestampType = { start_ms: number; end_ms: number; text: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
