
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * List all available audio-input devices.
 * 
 * Routes through `Orchestrator::list_devices`, which wraps the FFI-bound
 * cpal enumeration in `spawn_blocking`. This keeps `ipc-bridge`'s
 * dependency table honest: it depends on `orchestrator`, not directly on
 * `audio-capture`.
 */
async listDevices() : Promise<Result<AudioDevice[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start a new recording session.
 * 
 * `device_id = None` → use the device configured in settings, or the OS
 * default if none is configured.
 * 
 * Returns the new `MeetingId` on success.
 */
async startRecording(deviceId: string | null) : Promise<Result<MeetingId, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_recording", { deviceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pre-load the routed ASR model so the first record is not a cold ~29 s load
 * (live-test UX T2).
 * 
 * Routes to `Orchestrator::prewarm_asr`, which resolves the engine from the
 * `transcription_language` setting and builds the backend on `spawn_blocking`
 * into a process-held cache the first `start()` consumes. Idempotent and
 * non-blocking-at-start (no download; a not-yet-downloaded model warms nothing).
 * The webview calls this when the recording/meeting workspace opens so the model
 * is ready before the user presses Start. Returns `()` even on a build failure —
 * the lazy worker-init path remains the fallback, so prewarm is best-effort.
 */
async prewarmAsr() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("prewarm_asr") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pause the current recording.
 */
async pauseRecording() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume after a pause.
 */
async resumeRecording() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the current recording and finalise the meeting.
 * 
 * Returns the completed `MeetingMeta` on success.
 * 
 * After the orchestrator finalises the meeting folder, this also **upserts the
 * libsql index** (FR-33) so the just-recorded meeting appears in
 * `list_meetings` **in the same session** — without waiting for the next
 * app-start `rebuild_from_disk`. The orchestrator stays decoupled from the
 * index (it does not own one); the `ipc-bridge` owns the index handle in
 * `IpcState`, so the upsert lives here. See `architecture/components.md`,
 * `ipc-bridge` "Phase 4 additions — stop-upsert".
 * 
 * The blocking transcript read (for the list excerpt) runs on `spawn_blocking`
 * per the threading model; the async index `upsert` is awaited, never
 * `block_on`'d (the no-`block_on`-in-command-handlers rule).
 * 
 * An index-upsert failure is logged and swallowed — the recording itself is
 * safely persisted on disk and the index is a derived cache that the next
 * startup `rebuild_from_disk` will reconcile, so a failed upsert must not turn
 * a successful stop into an error.
 */
async stopRecording() : Promise<Result<MeetingMeta, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return a snapshot of the current recording state.
 */
async getRecordingState() : Promise<Result<RecordingState, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recording_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the current application settings.
 */
async getSettings() : Promise<Result<Settings, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist updated application settings.
 * 
 * Broadcasts the change to all `SettingsHandle` subscribers.
 */
async updateSettings(settings: Settings) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all known models with their current runtime status.
 * 
 * Routes through `Orchestrator::list_models`, which wraps `ModelRegistry::list_models`
 * so that `ipc-bridge` does not need a direct `model-registry` dependency.
 */
async listModels() : Promise<Result<ModelStatus[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ensure a model is downloaded and hash-verified.
 * 
 * Returns `Ok(())` when the model is ready for use. Starts a download if the
 * model is absent; the webview tracks granular progress via
 * `AppEvent::ModelDownloadProgress` events emitted on the broadcast channel.
 * 
 * Routes through `Orchestrator::ensure_model`, preserving the dependency-table
 * invariant that `ipc-bridge` does not depend directly on `model-registry`.
 */
async ensureModel(modelId: ModelId) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist a meeting's notes (`notes.json` + `notes.md`).
 * 
 * Routes **directly** to `persistence::NotesStore` against
 * `IpcState::meetings_dir` — notes I/O is independent of the live recording
 * pipeline (see `architecture/components.md`, `persistence` "Phase 3 surface
 * growth — notes"), so the orchestrator is not involved. The blocking
 * filesystem write runs on `spawn_blocking` per the threading model.
 * 
 * `notes_json` is parsed from a `String` into a `serde_json::Value`; an
 * invalid JSON string is rejected as `AppError::InvalidInput`.
 */
async saveNotes(meetingId: MeetingId, notesJson: string, notesMarkdown: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_notes", { meetingId, notesJson, notesMarkdown }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load a meeting's persisted notes, or `None` when no notes have been saved.
 * 
 * Routes directly to `persistence::NotesStore`; the loaded opaque
 * `serde_json::Value` is re-serialised back to a `String` for the wire (see
 * [`NotesDocument`]).
 */
async loadNotes(meetingId: MeetingId) : Promise<Result<NotesDocument | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_notes", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all meetings for the meeting-list view (FR-33), most-recent first.
 * 
 * Reads straight from the libsql `index.db` ([`MeetingIndex::list_meetings`])
 * — a cheap projection that never loads a meeting's full transcript. The index
 * is async (libsql/tokio); the future is awaited here, never `block_on`'d.
 */
async listMeetings() : Promise<Result<MeetingListEntry[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_meetings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a meeting, returning its full restorable [`MeetingState`]
 * (metadata + transcript + optional notes).
 * 
 * Resolves the per-meeting folder under `IpcState::meetings_dir` and assembles
 * the state via `persistence::read_meeting_state`. The blocking `std::fs` reads
 * run on `spawn_blocking` per the threading model — the index is not consulted
 * (the folder is authoritative for the full state).
 */
async openMeeting(meetingId: MeetingId) : Promise<Result<MeetingState, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_meeting", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a meeting: updates `metadata.json` (authoritative) then the index row.
 * 
 * Routes to `persistence::meeting_ops::rename_meeting`, which keeps the on-disk
 * folder and the index consistent (see `architecture/components.md`,
 * `persistence` "Phase 4 surface growth — meeting ops").
 */
async renameMeeting(meetingId: MeetingId, title: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_meeting", { meetingId, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a meeting: removes the folder then the index row.
 * 
 * Routes to `persistence::meeting_ops::delete_meeting`.
 */
async deleteMeeting(meetingId: MeetingId) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_meeting", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-run transcription for a meeting offline (FR-33 action).
 * 
 * Routes to `Orchestrator::re_transcribe`, which decodes the meeting audio and
 * drives the same batched-VAD + ASR pipeline the live recorder uses, rewrites
 * `transcript.json`, refreshes the index row, and emits
 * `AppEvent::TranscriptSegment` events. Refused while a recording is in
 * progress (the orchestrator returns `AppError::InvalidInput`). The index
 * handle is shared from `IpcState` so the orchestrator need not own one.
 */
async reTranscribe(meetingId: MeetingId) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("re_transcribe", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run summarisation for a meeting (FR-30): produce `summary.md` and emit
 * `AppEvent::SummaryReady`.
 * 
 * Pipeline:
 * 1. Resolve the LLM model id — `settings.llm_model_id` if set, else the
 * bundled default [`DEFAULT_LLM_MODEL_ID`].
 * 2. Resolve the model **directory** via `Orchestrator::ensure_model_path`
 * (downloads + verifies when absent). This keeps the `model-registry` edge
 * in the orchestrator — there is **no** `orchestrator → summariser` edge;
 * the summariser is loaded here, in `ipc-bridge` (the granted
 * `ipc-bridge → summariser` edge).
 * 3. Open a [`LlamaSummariser`] over the single `.gguf` in that directory
 * (skipping any `mmproj-*`), read the transcript + notes markdown, run the
 * summary, and write `summary.md` — **all on `spawn_blocking`** because the
 * summariser's `open` + `summarise` are heavy and synchronous (the
 * threading-model rule: inference on `spawn_blocking`, never in a handler).
 * 4. Emit `AppEvent::SummaryReady { meeting_id }` on the shared `event_tx` so
 * the summary view re-reads the persisted markdown.
 * 
 * The model resolution (`ensure_model_path`) is awaited on the async worker
 * (it may download); only the synchronous summariser work runs on
 * `spawn_blocking`.
 */
async summariseMeeting(meetingId: MeetingId) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summarise_meeting", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a meeting's persisted summary markdown, or `None` when none exists.
 * 
 * Routes directly to `persistence::read_summary` (a blocking `std::fs` read on
 * `spawn_blocking`).
 */
async getSummary(meetingId: MeetingId) : Promise<Result<string | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_summary", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist an edited summary back to `summary.md` (FR-30).
 * 
 * Routes directly to `persistence::write_summary` (atomic tmp+rename) on
 * `spawn_blocking`.
 */
async saveSummary(meetingId: MeetingId, summaryMarkdown: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_summary", { meetingId, summaryMarkdown }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-run speaker diarization for a meeting offline (Phase 6, FR-11 action).
 * 
 * Routes to `Orchestrator::rediarize`, which decodes the meeting's
 * pause-INCLUDING PCM, runs the bundled `SherpaDiarizer` over the stored
 * transcript segments (resolving both diarize model directories via
 * `model-registry`), rewrites `transcript.json` with the overlaid
 * `speaker_id`s, updates `metadata.json`'s `{ speaker_count, diarizer }`,
 * refreshes the index row's `speaker_count`, and emits
 * `AppEvent::DiarizationComplete { meeting_id, speaker_count }` — the event is
 * emitted by the **orchestrator** (not here), on the shared bus the forwarder
 * subscribes to. Refused while a recording is in progress (the orchestrator
 * returns `AppError::InvalidInput`).
 * 
 * The `model-registry` edge stays inside the orchestrator (the diarizer is
 * built there) — there is **no** `ipc-bridge → diarizer` Cargo edge;
 * `ipc-bridge` routes via the orchestrator. The shared `IpcState::index` handle
 * is passed into the call so the orchestrator refreshes the index row without
 * owning an index of its own.
 */
async rediarizeMeeting(meetingId: MeetingId) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rediarize_meeting", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a user message to the chat agent for a meeting, streaming the reply.
 * 
 * Creates or loads the chat [`ChatSession`], appends the user message, and
 * **spawns the turn on a background task**, returning the session id
 * immediately. The turn streams to the webview via the chat `AppEvent`s
 * (`ChatToken` / `ChatToolCall` / `ChatToolResult` / `ChatTurnComplete` /
 * `ChatError`) on the shared bus; the updated session is persisted via
 * [`ChatStore`] at turn end. A second `send_chat_message` for a session whose
 * turn is still running is rejected with `InvalidInput { "session busy" }`
 * (§6 — single in-flight turn per session).
 * 
 * The engine work runs on `spawn_blocking` (the LLM is FFI-bound); tool
 * dispatch re-enters async via a captured `Handle::block_on` for the dispatch
 * step only (§4.5 — the one place async/sync cross).
 */
async sendChatMessage(meetingId: MeetingId | null, sessionId: ChatSessionId | null, message: string) : Promise<Result<ChatSessionId, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_chat_message", { meetingId, sessionId, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel the in-flight chat turn for a session (P1).
 * 
 * Raises the per-session [`chat_agent::CancelFlag`] registered by
 * `send_chat_message`; the engine's decode loop observes it between tokens,
 * stops, and the driver emits the terminal `ChatTurnComplete` with the partial
 * text (cancellation is a user action, not a `ChatError`) and clears the
 * in-flight guard. Idempotent: a session with no running turn (no registered
 * flag) is a no-op success — the UI can call this freely to clear a stuck
 * "Sending…" state.
 */
async cancelChatTurn(sessionId: ChatSessionId) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_chat_turn", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get one chat session for a meeting, or `None` when it does not exist.
 */
async getChatSession(meetingId: MeetingId, sessionId: ChatSessionId) : Promise<Result<ChatSession | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_chat_session", { meetingId, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all chat sessions for a meeting, most-recently-updated first.
 */
async listChatSessions(meetingId: MeetingId) : Promise<Result<ChatSession[], IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chat_sessions", { meetingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete one chat session for a meeting (idempotent).
 */
async deleteChatSession(meetingId: MeetingId, sessionId: ChatSessionId) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_chat_session", { meetingId, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The live MCP server endpoint (URL + bearer token) for the Settings → MCP
 * pane (Phase 10). `None` when the MCP server is disabled or not yet listening.
 * 
 * The bearer token is sensitive and crosses the IPC boundary ONLY here, on this
 * explicit read — it is never on the event bus, never logged, and not baked
 * into the bindings. The pane reveals it on user request.
 * 
 * v1 has no live token-rotation command: the token is generated once and
 * persisted to `{app-data}/mcp_token`, and the listener is spawned once at
 * startup. Rotating the token (delete the file → restart) is therefore
 * restart-required, consistent with the rest of the MCP lifecycle (enable /
 * port / write-tools changes are also restart-required for v1). The pane copy
 * states this; it does NOT offer a live regenerate control (C2).
 */
async getMcpServerInfo() : Promise<Result<McpServerInfo | null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_mcp_server_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
appEventPayload: AppEventPayload
}>({
appEventPayload: "app-event-payload"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * The shared error type that crosses crate boundaries.
 * 
 * Per-crate `Error` enums (defined with `thiserror` in their owning
 * crate) provide structured `From` impls into `AppError`. The webview
 * only ever sees `AppError`. Variants have stable discriminants — the
 * TypeScript binding is generated from this enum, so renaming or
 * removing a variant is a breaking IPC change.
 */
export type AppError = { code: "io"; context: string } | { code: "model_load"; model_id: string; context: string } | { code: "model_not_found"; model_id: string } | { code: "model_download"; context: string } | { code: "inference"; backend: string; context: string } | { code: "invalid_input"; context: string } | { code: "cancelled" } | { code: "unsupported"; context: string } | { code: "internal"; context: string }
/**
 * Events emitted from the Rust core to the webview via tauri-specta.
 * 
 * Adding a variant requires updating `ipc-bridge` (encoder), the webview
 * IPC client (decoder), and re-running the bindings generation step.
 */
export type AppEvent = 
/**
 * Audio meter sample emitted at ~30 Hz while recording. Carries both
 * peak and RMS so the UI can pick the rendering it wants without an
 * extra round-trip.
 */
{ kind: "audio_meter"; frame: AudioMeterFrame } | 
/**
 * The available audio-input device list changed (hotplug or default
 * device switch). The webview should re-query `list_devices`.
 */
{ kind: "devices_changed" } | 
/**
 * Recording state changed.
 */
{ kind: "state_changed"; state: RecordingState } | 
/**
 * A new transcript segment was produced.
 */
{ kind: "transcript_segment"; meeting_id: MeetingId; segment: Segment } | 
/**
 * The live recording clock advanced. Emitted at a throttled rate
 * (~5 Hz) while recording. `clock_ms` is the capture-sample,
 * pause-*excluding* offset from the start of the recording — the same
 * timeline as `Segment::start_ms` and `AudioChunk::start_ms`. The notes
 * editor stamps paragraph anchors (`data-anchor-ms`) from this value so
 * anchors line up with transcript segments; do NOT derive anchors from
 * `Date.now() - started_at_ms` (that is pause-including wall-clock).
 */
{ kind: "recording_clock"; meeting_id: MeetingId; clock_ms: number } | 
/**
 * Diarization finished assigning speakers to a meeting's segments.
 */
{ kind: "diarization_complete"; meeting_id: MeetingId; speaker_count: number } | 
/**
 * Summary generation finished; `summary.md` now exists for this meeting.
 */
{ kind: "summary_ready"; meeting_id: MeetingId } | 
/**
 * A stopped meeting finished finalising on disk (`transcript.json` +
 * `metadata.json` written, `audio.opus` closed). The webview refreshes the
 * meeting list so the just-recorded meeting appears. Distinct from
 * `StateChanged { Idle }`: the list refresh keys on the meeting being
 * *ready on disk*, which is exactly when this fires.
 */
{ kind: "meeting_finalised"; meeting_id: MeetingId } | 
/**
 * An offline re-transcribe finished rewriting `transcript.json`. The webview
 * re-reads the meeting's transcript (list excerpt + any open-meeting view),
 * mirroring `DiarizationComplete`. Emitted by both the user-triggered
 * re-transcribe and the background post-stop repair, so a repaired
 * transcript surfaces without a manual refresh even when diarization is off.
 */
{ kind: "transcript_ready"; meeting_id: MeetingId } | 
/**
 * A long-running per-meeting operation made progress. The webview renders a
 * per-meeting-row indicator: a determinate bar when `fraction` is `Some`
 * (0.0..=1.0), an indeterminate spinner when `None`. Emitted throttled by
 * the producing op; a terminal `DiarizationComplete` / `TranscriptReady` /
 * `SummaryReady` clears the indicator. Rides the existing `AppEventPayload`
 * tag machinery — no second event registration. See
 * `architecture/cross-cutting.md` — "Operation progress".
 */
{ kind: "operation_progress"; meeting_id: MeetingId; op: OperationKind; fraction: number | null; label: string } | 
/**
 * Model download progress, used by the first-run flow.
 */
{ kind: "model_download_progress"; model_id: ModelId; bytes_done: number; bytes_total: number | null } | 
/**
 * A newer release is available (the updater's check found one). The
 * webview shows an update-available prompt. Emitted by app-main's
 * `tauri-plugin-updater` integration; see `architecture/cross-cutting.md`
 * "Auto-update".
 */
{ kind: "update_available"; version: string; notes: string | null } | 
/**
 * Update-download progress while applying an accepted update. `total_bytes`
 * is `None` when the server sends no content length.
 */
{ kind: "update_progress"; downloaded_bytes: number; total_bytes: number | null } | 
/**
 * User-visible settings changed; subscribers should re-read.
 */
{ kind: "settings_changed" } | 
/**
 * A recoverable error occurred during a background task. The pipeline
 * continues; the webview shows a notification.
 */
{ kind: "error_occurred"; error: AppError } | 
/**
 * One streamed token (or token fragment) of the assistant's reply for the
 * in-flight turn. Lossy: a dropped delta is reconciled by the `final_text`
 * carried on `ChatTurnComplete` (see `cross-cutting.md`).
 */
{ kind: "chat_token"; session_id: ChatSessionId; turn_id: number; token: string } | 
/**
 * The assistant requested a tool call mid-turn. `args_json` is the tool's
 * arguments serialised as a JSON string (the repo's "Value crosses as
 * String" rule).
 */
{ kind: "chat_tool_call"; session_id: ChatSessionId; turn_id: number; tool: string; args_json: string } | 
/**
 * A tool call finished. `ok` is `false` when the tool errored; `summary` is
 * the one-line human/LLM-facing render shown on the UI tool card.
 */
{ kind: "chat_tool_result"; session_id: ChatSessionId; turn_id: number; tool: string; ok: boolean; summary: string } | 
/**
 * The assistant turn finished. `final_text` carries the FULL reconciled
 * reply so the store can overwrite regardless of any dropped `ChatToken`
 * deltas (lossy-broadcast mitigation).
 */
{ kind: "chat_turn_complete"; session_id: ChatSessionId; turn_id: number; final_text: string } | 
/**
 * The chat turn failed. `message` is a stable human-readable string the
 * webview surfaces in the chat pane.
 */
{ kind: "chat_error"; session_id: ChatSessionId; message: string } | 
/**
 * The driver's sliding window evicted the oldest non-pinned messages to
 * keep the conversation within the context budget (Phase 9).
 * `dropped_turns` is the number of history messages dropped (snapped to a
 * user-message group boundary, CQ2). The webview shows a "history trimmed"
 * affordance so the user knows older turns no longer inform the agent. The
 * pinned system head (turn 0) is never evicted.
 */
{ kind: "chat_context_trimmed"; session_id: ChatSessionId; dropped_turns: number } | 
/**
 * The in-process MCP server bound its loopback Streamable HTTP listener.
 * `app-main` emits this after `mcp_server::serve` returns the bound addr so
 * the Settings → MCP pane can show the live endpoint URL. The bearer token
 * is deliberately NOT carried on the event bus (it is revealed only via the
 * `get_mcp_server_info` command on explicit user request); see
 * `architecture/cross-cutting.md` — "MCP transport".
 */
{ kind: "mcp_server_listening"; url: string }
/**
 * Typed wrapper that gives `AppEvent` a stable tauri-specta event name.
 * 
 * The `Event` derive assigns the wire name `"app-event-payload"`. The
 * `#[serde(transparent)]` attribute means the wrapper is invisible on the
 * wire — the JSON shape is exactly `AppEvent`'s own tagged-enum
 * representation.
 */
export type AppEventPayload = AppEvent
/**
 * One audio-input device exposed to the device-picker UI.
 * 
 * `id` is a stable, opaque string the IPC layer round-trips back to
 * `audio-capture` to select the device. Format is implementation-defined
 * (cpal device-name plus host index on the Rust side). `name` is the
 * display label; `is_default` reflects the OS's default-input choice at
 * query time.
 */
export type AudioDevice = { id: string; name: string; is_default: boolean }
/**
 * Audio-file format descriptor captured at write time. Phase 1 writes
 * Opus 16 kHz mono; downstream phases re-decode using these fields.
 */
export type AudioFormat = { codec: string; sample_rate: number; channels: number; bitrate_kbps?: number | null }
/**
 * One audio-meter sample emitted at ~30 Hz while recording.
 * 
 * `peak` is the maximum absolute sample magnitude in [0.0, 1.0] over the
 * most-recent meter window (~33 ms of audio). `rms` is the root-mean-square
 * over the same window. Consumers may render either; both are cheap to
 * compute alongside capture.
 */
export type AudioMeterFrame = { peak: number; rms: number }
/**
 * One persisted chat message (the wire / on-disk shape).
 * 
 * Distinct from `chat-agent`'s engine-internal message: this is the durable,
 * specta-typed record the webview renders and `persistence::ChatStore`
 * serialises. `turn_id` is the per-session monotonic turn counter the streaming
 * chat `AppEvent`s also carry, so the UI can correlate a stored message with
 * the deltas it saw live. `tool_name` is present only on `Tool` messages (the
 * name of the tool whose result the message carries). `tool_calls` is present
 * only on an `Assistant` message that requested tools — the carrier that keeps
 * a reloaded multi-tool turn a valid OpenAI sequence (CQ1).
 */
export type ChatMessage = { role: ChatRole; content: string; 
/**
 * For a `Tool` message: the tool whose result this message carries.
 * `None` for system/user/assistant messages.
 */
tool_name?: string | null; 
/**
 * For a `Tool` message: the OpenAI tool-call id this result answers — the
 * id of the matching entry in the preceding assistant message's
 * `tool_calls` (CQ1). Persisted so a reloaded turn re-links each tool
 * result to its call rather than synthesising an id that no longer matches
 * the assistant `tool_calls`. `None` for non-tool messages.
 */
tool_call_id?: string | null; 
/**
 * For an `Assistant` message: the tool calls it requested (CQ1). Empty for
 * every other message and for a plain assistant free-text reply. Defaulted
 * so an older on-disk session (written before this field existed) reloads.
 */
tool_calls: ToolCallRecord[]; 
/**
 * The per-session monotonic turn this message belongs to. The user message
 * and the assistant/tool messages produced answering it share one `turn_id`
 * (the same value the `ChatToken`/`ChatTurnComplete` events carry).
 */
turn_id: number }
/**
 * The role of one persisted chat message as it crosses the IPC boundary and is
 * stored on disk.
 * 
 * This is the **wire / persisted** role, distinct from `chat-agent`'s
 * engine-internal `Role` (which serialises the same snake_case names for the
 * oaicompat template but is a different type owned by that crate). The driver
 * (`ipc-bridge`) maps between the engine's history and these persisted/wire
 * shapes at its boundary. `serde` snake_case so the TS binding mirrors the
 * engine's role names.
 */
export type ChatRole = 
/**
 * The session's system prompt (turn 0): persona + meeting context.
 */
"system" | 
/**
 * A message the user typed.
 */
"user" | 
/**
 * An assistant reply (the model's final text for a turn).
 */
"assistant" | 
/**
 * A tool-result message appended after the driver ran a tool call.
 */
"tool"
/**
 * A persisted chat session for one meeting.
 * 
 * `persistence::ChatStore` stores this under
 * `{meetings_dir}/{meeting_id}/chat/{session_id}.json` (atomic tmp+rename); the
 * chat IPC commands load/save it. `meeting_id` is optional so a session may be
 * un-scoped (an MCP-originated session that targets no specific meeting);
 * `title` is optional so an untitled session round-trips. Timestamps are RFC
 * 3339 strings to avoid pulling a time crate into `common`, mirroring
 * `MeetingMeta::started_at`.
 */
export type ChatSession = { id: ChatSessionId; meeting_id?: MeetingId | null; title?: string | null; messages: ChatMessage[]; created_at: string; updated_at: string }
/**
 * Stable identifier for a chat session on disk. UUIDv4. Mirrors [`MeetingId`].
 * 
 * A chat session is meeting-scoped; `persistence` stores its turns under
 * `{meetings_dir}/{meeting_id}/chat/{session_id}.json` (Phase 9 §7). The
 * streaming chat `AppEvent`s carry this so the webview store routes deltas to
 * the right session.
 */
export type ChatSessionId = string
/**
 * GPU-acceleration mode (replaces the old `gpu_acceleration: bool`).
 * 
 * `Auto` (the default) probes GPU VRAM at each model load and offloads a model
 * to the GPU only when it fits, falling back to CPU otherwise. `On`/`Off` are
 * hard overrides that NEVER consult the probe — `On` forces full GPU offload
 * (the old `true`), `Off` forces CPU (the old `false`). Only effective in a
 * build compiled with a GPU feature (`vulkan`/`metal`/…); a CPU-only build
 * always runs on CPU regardless. See `architecture/cross-cutting.md` — "GPU
 * portability".
 */
export type GpuAcceleration = 
/**
 * Probe VRAM per model load; GPU iff it fits, else CPU. The new default.
 */
"auto" | 
/**
 * Force GPU offload (no probe) — the old `gpu_acceleration = true`.
 */
"on" | 
/**
 * Force CPU (no probe) — the old `gpu_acceleration = false`.
 */
"off"
/**
 * Error type returned from every Tauri command in `ipc-bridge`.
 * 
 * Carries the same discriminants as `common::AppError` and serialises to the
 * same JSON shape (`{"code": "...", ...}`), so the TypeScript binding is
 * stable even though the derive lives here rather than in `common`.
 */
export type IpcError = { code: "io"; context: string } | { code: "model_load"; model_id: string; context: string } | { code: "model_not_found"; model_id: string } | { code: "model_download"; context: string } | { code: "inference"; backend: string; context: string } | { code: "invalid_input"; context: string } | { code: "cancelled" } | { code: "unsupported"; context: string } | { code: "internal"; context: string }
/**
 * The live MCP endpoint surfaced to the Settings → MCP pane via
 * `get_mcp_server_info` (Phase 10). The bearer `token` is sensitive: it is
 * never logged and only crosses the IPC boundary on this explicit read.
 */
export type McpServerInfo = { 
/**
 * The full Streamable HTTP endpoint URL, e.g. `http://127.0.0.1:8765/mcp`.
 */
url: string; 
/**
 * The bearer token the bridge must present.
 */
token: string }
/**
 * Stable identifier for a meeting on disk. UUIDv4.
 */
export type MeetingId = string
/**
 * A summary row for the meeting-list view (FR-33). Cheap to query from the
 * `persistence` index without loading a meeting's full transcript.
 */
export type MeetingListEntry = { id: MeetingId; title: string; 
/**
 * RFC3339 start timestamp (wall-clock), mirroring `MeetingMeta::started_at`.
 */
started_at: string; duration_ms: number; speaker_count: number; 
/**
 * Short transcript excerpt for the list preview, when available.
 */
excerpt?: string | null }
/**
 * Per-meeting metadata persisted as `metadata.json`.
 * 
 * Timestamps are ISO 8601 strings to avoid pulling `chrono` into `common`.
 * Consumers parse as needed.
 */
export type MeetingMeta = { uuid: MeetingId; title: string; started_at: string; ended_at: string | null; duration_ms: number; speaker_count: number; audio_format: AudioFormat; asr_model: ModelDescriptor | null; llm_model: ModelDescriptor | null; diarizer: ModelDescriptor | null; 
/**
 * User-set display names for identified speakers, keyed by the diarizer's
 * label (e.g. `"A"` → `"Alice"`). Written by the `set_speaker_name` chat
 * tool and overlaid at read time; cleared by re-diarization (which can
 * re-letter speakers, see `cross-cutting.md` "Agent chat loop"). Phase 9.
 * 
 * `#[serde(default, skip_serializing_if = …)]` so existing `metadata.json`
 * (written before the field existed) still deserialises and the wire shape
 * only grows when the map is non-empty.
 */
speaker_names: Partial<{ [key in string]: string }>; app_version: string }
/**
 * The full restorable state of a meeting, assembled by `persistence` for
 * `open_meeting`: metadata, transcript segments, and the notes document
 * (absent when the meeting has no saved notes yet).
 */
export type MeetingState = { meta: MeetingMeta; transcript: Segment[]; notes?: NotesDocument | null }
export type ModelDescriptor = { name: string; quantisation: string | null; version: string }
/**
 * Stable identifier for a model in the registry.
 * 
 * Examples: `"qwen3-asr-1.7b-q8_0"`, `"qwen2.5-3b-instruct-q4_k_m"`,
 * `"silero-vad-v4"`, `"sherpa-pyannote-segmentation-3-0"`.
 */
export type ModelId = string
/**
 * Coarse model classification — drives the per-kind cache subdirectory
 * under `{app-data}/models/{kind}/` (see `architecture/cross-cutting.md`
 * "Filesystem layout").
 */
export type ModelKind = "asr" | "llm" | "diarize"
export type ModelStatus = { id: ModelId; kind: ModelKind; display_name: string; status: ModelStatusState; 
/**
 * SPDX licence identifier of the underlying weights, copied verbatim
 * from the manifest entry's `license` ("apache-2.0", "mit", etc.).
 * Surfaced in the About dialog so the bundled-model list never drifts
 * from `resources/models.json`.
 */
license: string }
/**
 * Runtime state of one model on this user's machine.
 */
export type ModelStatusState = 
/**
 * Files are present and hashes match. `local_dir` is the cache
 * directory absolute path.
 */
{ state: "available"; local_dir: string } | 
/**
 * Files are missing or partial. `bytes_present` and `bytes_total`
 * are summed across the manifest's `files`.
 */
{ state: "missing"; bytes_present: number; bytes_total: number } | 
/**
 * A download is in progress. The webview tracks granular progress
 * via `AppEvent::ModelDownloadProgress` events; this state is the
 * snapshot at query time.
 */
{ state: "downloading"; bytes_done: number; bytes_total: number } | 
/**
 * A previous download or hash check failed. `message` is a stable
 * human-readable string suitable for surfacing in UI.
 */
{ state: "failed"; message: string }
/**
 * The notes document as it crosses the IPC boundary.
 * 
 * `notes_json` is the Tiptap document serialised to a JSON **string** —
 * `serde_json::Value` does not derive `specta::Type`, so the opaque document
 * rides the wire as a string and the webview owns its (de)serialisation.
 * `persistence` stores it verbatim (the transcript-chip opacity guarantee).
 * This is the canonical wire-facing notes carrier; `ipc-bridge` re-uses it.
 */
export type NotesDocument = { notes_json: string; notes_markdown: string }
/**
 * Which long-running operation an [`AppEvent::OperationProgress`] event reports.
 * 
 * Determinate (a `fraction` is available): `ReTranscribe` (samples processed /
 * total kept samples) and `Summarise` (tokens generated / max tokens).
 * Indeterminate (`fraction = None`, one opaque FFI compute call):
 * `Rediarize` and the `Finalise` drain.
 */
export type OperationKind = 
/**
 * Offline re-transcribe over the full `audio.opus` (determinate).
 */
"re_transcribe" | 
/**
 * LLM summary generation (determinate; tokens / max-tokens).
 */
"summarise" | 
/**
 * Speaker (re-)identification — internally "diarization" (indeterminate).
 */
"rediarize" | 
/**
 * The post-stop finalise drain (indeterminate).
 */
"finalise"
/**
 * Top-level state of the recording pipeline. Emitted to the webview on
 * transitions via `AppEvent::StateChanged`.
 * 
 * **Timestamp semantics:** `started_at_ms` and `paused_at_ms` are
 * **wall-clock milliseconds since the Unix epoch** (UTC), not
 * recording-clock offsets. The webview can compute live elapsed-recording
 * duration as `Date.now() - started_at_ms` (subtracting accumulated
 * pause-time client-side if needed). Phase-internal timestamps that are
 * genuinely recording-clock (e.g. `Segment::start_ms`, `AudioChunk::start_ms`)
 * remain recording-clock — those are a different namespace and carry the
 * `_ms` suffix without the `_at` infix.
 * 
 * **Do NOT use `Date.now() - started_at_ms` as a paragraph-anchor source.**
 * That wall-clock delta is pause-*including* and drifts from the audio
 * timeline. Notes paragraph anchors must be stamped from
 * `AppEvent::RecordingClock { clock_ms }`, which is the capture-sample,
 * pause-*excluding* clock (same origin as `Segment::start_ms`). The
 * `started_at_ms` recipe above is for elapsed-time *display* only.
 */
export type RecordingState = { kind: "idle" } | { kind: "recording"; meeting_id: MeetingId; started_at_ms: number } | { kind: "paused"; meeting_id: MeetingId; paused_at_ms: number } | { kind: "stopping"; meeting_id: MeetingId } | 
/**
 * The recorder is busy but not capturing: either a just-stopped meeting is
 * finalising in the background (the live ASR backlog drains and
 * `transcript.json` / `metadata.json` / `audio.opus` are written), or an
 * offline re-transcribe / re-diarize pass holds the recorder (the automatic
 * post-stop repairs and the user-triggered actions both claim the slot).
 * The UI stays responsive during this window — only starting a NEW recording
 * waits. After a stop, `Idle` plus `AppEvent::MeetingFinalised` fire on
 * completion; an offline pass returns to `Idle` when it finishes.
 */
{ kind: "finalising"; meeting_id: MeetingId }
/**
 * One transcript segment with optional speaker assignment.
 * 
 * Speaker is populated by the `Diarizer` impl post-hoc; ASR backends
 * leave it `None`.
 */
export type Segment = { start_ms: number; end_ms: number; text: string; speaker_id?: string | null; confidence?: number | null; words: WordTimestamp[] }
/**
 * Application settings.
 * 
 * Fields added in later phases live in their respective phase plans.
 */
export type Settings = { 
/**
 * The preferred audio-input device, identified by the opaque id
 * returned by `audio-capture::AudioCaptureManager::list_devices`.
 * `None` means "use the OS default".
 */
input_device_id?: string | null; 
/**
 * UI colour-scheme preference.
 */
theme?: Theme; 
/**
 * Root directory for meeting data.  `None` means "use the platform
 * default app-data directory" (resolved by `app-main`).
 * 
 * `specta` lacks a built-in `Type` impl for `PathBuf`; the explicit
 * `#[specta(type = Option<String>)]` hint preserves the same wire
 * shape (UTF-8 path string or `null`) the manual mirror produced.
 */
data_directory?: string | null; 
/**
 * If `true`, the main window starts hidden; accessible via the tray icon.
 */
start_hidden?: boolean; 
/**
 * Notes-editor autosave interval, in seconds (FR-18/FR-35).
 * 
 * The editor debounces autosaves of `notes.json`/`notes.md` to this
 * cadence. Defaults to 5 s; an older store written before this field
 * existed deserialises to the default via `#[serde(default = ...)]`.
 */
autosave_interval_secs?: number; 
/**
 * Optional CUSTOM summary system prompt that OVERRIDES the selected
 * [`SummaryPreset`] (FR-28 / D4).
 * 
 * Empty by default (the common case): [`Settings::effective_summary_prompt`]
 * then returns `preset_prompt(self.summary_preset)`, so the preset picker
 * drives summarisation. A non-empty value is a user override and wins over
 * the preset. The `summariser` forwards the effective prompt verbatim as the
 * `system` message when generating `summary.md`.
 */
summary_system_prompt?: string; 
/**
 * Selected LLM model for summarisation (FR-35).
 * 
 * `None` means "use the bundled default model" (resolved by the
 * summariser against the model registry). The model is settings-selected,
 * never hard-coded; switching is a manifest + `llm_model_id` change. An
 * older store written before this field existed deserialises to `None`
 * via `#[serde(default)]`.
 */
llm_model_id?: ModelId | null; 
/**
 * Whether the post-recording diarization pass runs (FR-11).
 * 
 * Diarization is post-hoc and off by default: the orchestrator gates its
 * on-stop diarizer pass (and the user-triggered re-diarize) on this flag.
 * `#[serde(default)]` defaults to `false`; an older store written before
 * this field existed deserialises to `false`.
 */
diarization_enabled?: boolean; 
/**
 * Whether the first-run onboarding flow has been completed (Phase 7).
 * 
 * The webview gates the main UI behind this: `false` shows the onboarding
 * flow (welcome → model download → settings tour), which sets it `true` on
 * completion. `#[serde(default)]` defaults to `false`; an older store
 * written before this field existed deserialises to `false` (so existing
 * users see onboarding once on upgrade — acceptable for a pre-release).
 */
onboarding_completed?: boolean; 
/**
 * GPU-acceleration MODE (replaces the former `bool`).
 * 
 * `Auto` (the default) probes GPU VRAM at each model load and offloads a
 * model to the GPU only when it fits, else CPU; `On` forces GPU offload;
 * `Off` forces CPU. Only effective in a GPU-feature build
 * (`vulkan`/`metal`/`cuda`/`rocm`); a default CPU-only build always runs on
 * CPU. Migrates a legacy bool store: `true → Auto`, `false → Off` (see
 * [`deserialize_gpu_acceleration`]). `#[serde(default = ...)]` →  `Auto` when
 * the field is missing. See `architecture/cross-cutting.md` — "GPU
 * portability".
 */
gpu_acceleration?: GpuAcceleration; 
/**
 * Whether to capture and mix the system/call (loopback) audio alongside
 * the microphone, so a Teams-style call transcribes all participants.
 * 
 * When `true`, `audio-capture` ALSO opens the default render endpoint in
 * loopback mode, resamples it to 16 kHz mono, and SUMS it sample-wise with
 * the mic into the single `samples` stream the orchestrator drains;
 * downstream diarization separates the speakers. When `false`, behaviour is
 * mic-only.
 * 
 * `#[serde(default = ...)]` defaults to `true` — capturing the call is the
 * point of a meeting-notes app, so it is opt-OUT; an older store written
 * before this field existed deserialises to `true`. If the mic also picks
 * the call audio up from the speakers, mixing the loopback in doubles it
 * (echo), so the UI advises turning it off in that case. Loopback capture is
 * currently Windows-only; on other platforms enabling this logs a warning
 * and falls back to mic-only (never failing the recording). Echo
 * cancellation using the loopback as the reference signal is future work —
 * see `architecture/cross-cutting.md` — "Threading model".
 */
capture_system_audio?: boolean; 
/**
 * ASR language hint (Qwen3-ASR). A full English language name (e.g.
 * "English", "Spanish", "Japanese") forces that language via the
 * assistant-turn prefix; the sentinel "auto" disables forcing (auto-detect,
 * the pre-feature behaviour). Defaults to "English" (fixes the spurious-
 * Chinese bug). An older store deserialises to "English" via the default fn.
 */
transcription_language?: string; 
/**
 * Opt into the larger Qwen3-ASR-1.7B tier for the Qwen branch (broader +
 * better-multilingual accuracy) instead of the 0.6B CPU default. Only
 * affects languages that route to Qwen (the Parakeet branch ignores it);
 * see `common::asr_engine_for_language`. Off by default — it is a larger
 * download with a GPU-class footprint. An older store deserialises to
 * `false`. See `architecture/cross-cutting.md` — "ASR engine routing".
 */
prefer_large_asr_model?: boolean; 
/**
 * Whether the notes editor renders faint horizontal "writing paper" rules
 * behind the text. Presentation-only: the webview reads this and toggles a
 * class on the editor surface. The oxblood *vertical* margin rule that
 * divides the timestamp gutter from the writing column is structural and is
 * always shown regardless of this flag. `#[serde(default = ...)]` defaults
 * to `true`; an older store written before this field existed deserialises
 * to `true`.
 */
notes_paper_rules?: boolean; 
/**
 * Chat-agent system prompt (Phase 9). The chat engine forwards this
 * verbatim as the session's `system` message. `#[serde(default = ...)]`
 * defaults to a meeting-notes-assistant instruction; an older store
 * written before this field existed deserialises to that default. Added
 * to the hand-written `Default` impl.
 */
chat_system_prompt?: string; 
/**
 * Selected summary prompt preset (Phase 9 — D4). Drives the effective
 * summary prompt via [`preset_prompt`] UNLESS `summary_system_prompt` is a
 * non-empty user override (see [`Settings::effective_summary_prompt`]).
 * `#[serde(default)]` defaults to [`SummaryPreset::Default`] (the prior
 * behaviour); an older store deserialises to `Default`.
 */
summary_preset?: SummaryPreset; 
/**
 * Whether the in-process MCP server is started (Phase 10). Opt-in, **off by
 * default**, mirroring `external-ollama` / `capture_system_audio`. When
 * `true`, `app-main` binds the loopback Streamable HTTP MCP endpoint at
 * startup so an external MCP client can reach the shared tool layer. Toggling at runtime is a documented
 * restart-required for v1. `#[serde(default)]` defaults to `false`; an older
 * store written before this field existed deserialises to `false`. See
 * `architecture/cross-cutting.md` — "MCP transport".
 */
mcp_enabled?: boolean; 
/**
 * The loopback TCP port the MCP server binds (Phase 10 — D1). A FIXED
 * default (8765): only one app instance runs, so a stable port keeps an
 * external MCP client's saved URL valid across runs. User-editable.
 * `#[serde(default = ...)]` defaults to 8765; an older store deserialises to
 * 8765. See `architecture/cross-cutting.md` — "MCP transport".
 */
mcp_port?: number; 
/**
 * Whether write tools are exposed over MCP (Phase 10 — D3). **Off by
 * default = read-only over MCP.** Consulted at registry-projection time by
 * the MCP server: with it OFF, `tools/list` is read/compute tools + the
 * inter-agent tool only; with it ON, the reversible writes
 * (`set_speaker_name`, `rename_meeting`) join. `retranscribe_meeting` /
 * `rediarize_meeting` / any destructive tool stay internal-only regardless
 * (they are never `expose_over_mcp`). `#[serde(default)]` defaults to
 * `false`; an older store deserialises to `false`. See
 * `architecture/cross-cutting.md` — "MCP transport".
 */
mcp_write_tools?: boolean; 
/**
 * Auto-summarise a meeting after it stops + finalises (#68).
 * 
 * When `true` (the default), the post-stop background chain in `ipc-bridge`
 * runs summarisation as its THIRD step (after any re-transcribe /
 * re-identify-speakers pass) so the summary is ready without the user
 * pressing Summarise. Best-effort: an error is logged, like the other
 * passes. `#[serde(default = ...)]` defaults to `true`; an older store
 * written before this field existed deserialises to `true`, preserving the
 * new default for existing users. See `architecture/cross-cutting.md` — the
 * Agent/stop lifecycle.
 */
auto_summarise_on_stop?: boolean; 
/**
 * Preload the summary/chat LLM at app startup and keep it resident.
 * 
 * The summary path and the chat agent share ONE held `LlamaSummariser`
 * (loaded once, kept for the process lifetime). When `true` (the default),
 * `app-main` warms it in the background at startup IF the model is already
 * downloaded — so the first Summarise / chat is instant rather than paying a
 * multi-GB load. It NEVER triggers a download at startup (a not-yet-fetched
 * model is left to load on first use / after the onboarding download). When
 * `false`, the model loads on-demand on first use (the prior behaviour) — the
 * escape hatch for keeping idle memory low. `#[serde(default = ...)]`
 * defaults to `true`; an older store written before this field existed
 * deserialises to `true`.
 */
preload_summariser?: boolean }
/**
 * Built-in summary prompt presets (Phase 9 — D4).
 * 
 * Each preset maps to a built-in system prompt via [`preset_prompt`]. The
 * selected preset drives the effective summary prompt UNLESS the user sets a
 * custom override in `summary_system_prompt` (see
 * [`Settings::effective_summary_prompt`]). `Default` reproduces the prior
 * `summarise_meeting` behaviour exactly.
 */
export type SummaryPreset = 
/**
 * Structured summary: Summary / Key Decisions / Action Items. The prior
 * (pre-preset) default behaviour.
 */
"default" | 
/**
 * Like `Default` but explicitly omits greetings, small-talk and sign-off
 * chit-chat at the start and end of the meeting.
 */
"filter_chit_chat" | 
/**
 * Focus on decisions, action items and their owners.
 */
"action_items" | 
/**
 * A thorough, sectioned summary covering topics, discussion and outcomes.
 */
"detailed"
/**
 * UI colour-scheme preference.
 */
export type Theme = "light" | "dark" | 
/**
 * Follow the OS preference (default).
 */
"system"
/**
 * One tool call an assistant message requested, in the persisted/wire shape.
 * 
 * Mirrors `chat-agent`'s engine-internal `ToolCall` (`id` / `name` /
 * `arguments_json` — the repo's "arguments cross as a String, not a `Value`"
 * rule). Carried on an `Assistant` [`ChatMessage`] so a reloaded session
 * reconstructs the `assistant(tool_calls) → tool(result)` exchange the GGUF
 * tool template requires (CQ1) instead of an orphan `tool` message.
 */
export type ToolCallRecord = { 
/**
 * The OpenAI tool-call id the matching `Tool` message answers.
 */
id: string; 
/**
 * The tool name.
 */
name: string; 
/**
 * The tool arguments as a JSON-object string.
 */
arguments_json: string }
/**
 * Optional per-word timestamp data when the ASR model supports it.
 */
export type WordTimestamp = { start_ms: number; end_ms: number; text: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
