[package]
name = "audio-capture"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
meeting-app-common = { path = "../common" }
cpal = { workspace = true }
rubato = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }

[features]
test-source = []
